### PR TITLE
Use authorization header instead of adding to query

### PR DESCRIPTION
**Pull request by Radiicall**
This should avoid some logging issues when reporting bugs and also up the general security of the requests

### CODE REVIEW

**Comment by Radiicall** [comment]
@EmeryxWildfire Do you still have an emby server that you can test this on?

**Comment by Radiicall** [comment]
Package with new auth can be found at the bottom of [this page](https://github.com/Radiicall/jellyfin-rpc/actions/runs/10076599919)

**Comment by Nathan5471** [comment]
I tried it on an Emby server and it worked with a movie, is there something specific that needed to be tested?

**Comment by Radiicall** [comment]
> I tried it on an Emby server and it worked with a movie, is there something specific that needed to be tested?

Hey that's perfect thanks! I am testing a new way to do the authentication but I had to confirm that the solution i put in place for emby actually works

**Pull request merged**
